name: Triton CI

workspace:
  clean: all

pool:
  name: default

# Some variables
variables:
- name: venv
  value: venv

# Run CI when something pushed to master
trigger: none
# Run CI when a PR is created or updated from master
pr:
- master

# Pipeline
steps:
- script: |
    python -m pip install --upgrade pip
    pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 \
                -f https://download.pytorch.org/whl/torch_stable.html
    pip install matplotlib pandas
    cd python
    python setup.py install
  displayName: Setup python environment

- script: |
    cd python/bench
    python -m run 

- publish: python/bench/results
  artifact: Benchmarks

- script: |
    source $(venv)/bin/activate
    pip install pytest
    pytest .
  displayName: 'Run Python tests'