name: Triton CI

workspace:
  clean: all

pool:
  name: default

# Some variables
variables:
- name: venv
  value: venv

# Run CI when something pushed to master
trigger: none
# Run CI when a PR is created or updated from master
pr:
- master

# Pipeline
steps:
- script: |
    alias python='python3'
    cd python
    pip3 install -e .
  displayName: Setup python environment

- script: |
    cd python/bench
    python3 -m run 

- publish: python/bench/results
  artifact: Benchmarks

- script: |
    pytest .
  displayName: 'Run Python tests'