trigger: none
pr: none

jobs:
- job: linux

  workspace:
    clean: all

  timeoutInMinutes: 180

  pool: default

  steps:
    - bash: |
        set -o errexit
        python3 --version
        python3 -m pip install --upgrade pip
        pip3 install cibuildwheel==1.10.0
        pip3 install twine
      displayName: Install dependencies
    - bash: |
        #sed -i 's/name\=\"triton\"/name="triton-nightly"/g' python/setup.py
        export LATEST_DATE=$(git show -s --format=%ci `git rev-parse HEAD` | cut -d ' ' -f 1 | sed 's/-//g')
        sed -i -r "s/version\=\"(.*)\"/version=\"\1-dev"$LATEST_DATE"\"/g" python/setup.py
        echo "" >> python/setup.cfg
        echo "[build_ext]" >> python/setup.cfg
        echo "base-dir=/project" >> python/setup.cfg
      displayName: Patch setup.py
    - bash: |
        export CIBW_MANYLINUX_X86_64_IMAGE="manylinux_2_24"
        export CIBW_BEFORE_BUILD="pip install cmake \
                                  && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - \
                                  && wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz"
        export CIBW_BUILD="{cp,pp}3*-manylinux_x86_64"
        python3 -m cibuildwheel python --output-dir wheelhouse
      displayName: Build wheels
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
    - bash: |
        python3 -m twine upload wheelhouse/* --skip-existing -u $(PYPI_USERNAME) -p $(PYPI_PASSWORD) 
      displayName: Upload wheels to PyPI
    