trigger: none
pr: none

jobs:
- job: linux

  workspace:
    clean: all

  pool: default

  steps:
    - bash: |
        set -o errexit
        cd python
        python setup.py develop
      displayName: Install dependencies
    - bash: |
        cd docs
        make html
      displayName: Build docs
    - bash: |
        git checkout gh-pages
        sh ./update-website.sh
        git remote set-url origin git@github.com:ptillet/triton.git
        git push
      displayName: Publish docs
    