name: Documentation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Build-Documentation:
    runs-on: [self-hosted, V100]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PAT }}

      - name: Clear docs
        run: |
          rm -r /tmp/triton-docs
        continue-on-error: true

      - name: Build docs
        run: |
          cd docs
          sphinx-multiversion . _build/html/

      - name: Update docs
        run: |
          mkdir /tmp/triton-docs
          mv docs/_build/html/* /tmp/triton-docs/
          git checkout gh-pages
          cp -r CNAME /tmp/triton-docs/
          cp -r index.html /tmp/triton-docs/
          cp -r .nojekyll /tmp/triton-docs/
          rm -r *
          cp -r /tmp/triton-docs/* .
          git add .
          git commit -am "[GH-PAGES] Updated website"

      - name: Publish docs
        run: |
          git push origin gh-pages
