name: Documentation
on:
  workflow_dispatch:
  schedule:    
    - cron: "0 0 * * *"

jobs:

  Build-Documentation:
    
    runs-on: self-hosted

    steps:

      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Build docs
        run: |
          git fetch origin master:master
          git branch
          cd docs
          sphinx-multiversion . _build/html/

      - name: Publish docs
        run: |
          git checkout -b gh-pages origin/gh-pages
          sh ./update-website.sh
          eval `ssh-agent -s`
          DISPLAY=:0 SSH_ASKPASS=~/.ssh/give_pass.sh ssh-add ${{ secrets.SSH_KEY }} <<< ${{ secrets.SSH_PASS }}
          git remote set-url origin git@github.com:openai/triton.git
          git push
