name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master


jobs:

  Integration-Tests:
    
    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Triton
        run: |
          alias python='python3'
          cd python
          pip3 install -e .

      - name: Run benchmarks
        run: |
          cd python/bench
          python3 -m run 

      - name: Run unit tests
        run: |
          pytest .