name: Torchinductor

on:
  workflow_dispatch:

jobs:
  Runner-Preparation:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Prepare runner matrix
        id: set-matrix
        run: |
          echo '::set-output name=matrix::[["self-hosted", "A100"]]'

  Integration-Tests:
    needs: Runner-Preparation
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: ${{fromJson(needs.Runner-Preparation.outputs.matrix)}}
    steps:
      - name: Accuracy
        run: |
          ./.github/workflows/scripts/run_torchinductor_acc.sh
      - name: Performance
        run: |
          ./.github/workflows/scripts/run_torchinductor_perf.sh
